---
services:
  rserver:
    build:
      context: rserver
      dockerfile: Dockerfile
    # build: rserver/Dockerfile.alpine
    ports:
      - "3333:3333"
    healthcheck:
      test: ["CMD", "nc", "-v", "-z", "rserver", "3333"]
      interval: 10s
      timeout: 4s
      retries: 2
  rclient:
    build: rclient/.
    depends_on:
      rserver:
        condition: service_healthy
    links:
      - rserver
