# Makefile.toml

[tasks.build-rclient]
cwd = "./rclient/"
command = "cargo"
args = ["make", "all"]

[tasks.build-rserver]
cwd = "./rserver/"
command = "cargo"
args = ["make", "podman-image"]

[tasks.server-run]
description = "Lancement du serveur."
command = "podman"
args = ["run", "--replace", "--name", "rserver", "-ti", "--detach", "--rm", "--publish", "3333:3333", "pubuntu:latest"]
dependencies = ["build-rclient", "build-rserver"]

[tasks.all]
description = "Exécute toutes les tâches."
command = "./rclient/target/debug/rclient"
dependencies = ["server-run"]

[tasks.default]
alias = "all"

# sudo sed -i "s/^bind-address.*/bind-address=0.0.0.0/g" "/etc/mysql/mariadb.conf.d/50-server.cnf"